"""empty message

Revision ID: 4321fa9a9cca
Revises: 8d20e0242270
Create Date: 2017-09-11 13:58:34.810366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4321fa9a9cca'
down_revision = '8d20e0242270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DATETIME(), nullable=True))
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###
