"""empty message

Revision ID: 580c097a10eb
Revises: b298c5bd1a08
Create Date: 2017-09-12 13:46:02.356826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580c097a10eb'
down_revision = 'b298c5bd1a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
